version: '3.8'

services:
  auth-db:
    image: postgres:14-alpine
    container_name: auth-db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=authuser
      - POSTGRES_PASSWORD=authpassword
      - POSTGRES_DB=auth_db
    networks:
      - community_ride_share_network

  user-db:
    image: postgres:14-alpine
    container_name: user-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=useruser
      - POSTGRES_PASSWORD=userpassword
      - POSTGRES_DB=user_db
    networks:
      - community_ride_share_network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - auth-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=authuser
      - SPRING_DATASOURCE_PASSWORD=authpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - community_ride_share_network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=useruser
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - community_ride_share_network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
    networks:
      - community_ride_share_network

networks:
  community_ride_share_network:
    driver: bridge
