# Server port
server.port=8084

# Application Name
spring.application.name=payment-service

# Datasource Properties
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/payment_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:paymentuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:paymentpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
