# Server port
server.port=8083

# Application Name
spring.application.name=ride-service

# Datasource Properties
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/ride_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rideuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ridepassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
